#DEFINE ENABLE_REPLACE_FEATURE			.T.
#DEFINE GF_REPLACE_ERROR				'__GF__ERROR__IN__REPLACE__'

#DEFINE MATCHTYPE_FILENAME						'<<<Filename>>>'

#DEFINE MATCHTYPE_CLASS_DEF						'<<Class Def>>'
#DEFINE MATCHTYPE_CLASS_DESC					'<Class Desc>'

#DEFINE MATCHTYPE_METHOD_DEF					'<<Method Def>>'
#DEFINE MATCHTYPE_PROPERTY_DEF					'<<Property Def>>'

#DEFINE MATCHTYPE_CONTAINING_CLASS				'<Containing Class>'
#DEFINE MATCHTYPE_PARENTCLASS					'<Parent Class>'
#DEFINE MATCHTYPE_BASECLASS						'<Baseclass>'
#DEFINE MATCHTYPE_METHOD						'<Method>'
#DEFINE MATCHTYPE_METHOD_DESC					'<Method Desc>'
#DEFINE MATCHTYPE_PROPERTY						'<Property>'
#DEFINE MATCHTYPE_PROPERTY_DESC					'<Property Desc>'
#DEFINE MATCHTYPE_PROPERTY_NAME					'<Property Name>'
#DEFINE MATCHTYPE_PROPERTY_VALUE				'<Property Value>'

#DEFINE MATCHTYPE_PROCEDURE						'<Procedure>'
#DEFINE MATCHTYPE_FUNCTION						'<Function>'
#DEFINE MATCHTYPE_CONSTANT						'<Constant>'

#DEFINE MATCHTYPE_CLASS							'<Class>'
#DEFINE MATCHTYPE_BASECLASS						'<Baseclass>'
#DEFINE MATCHTYPE_NAME							'<Name>'

#DEFINE MATCHTYPE_CODE							'Code'
#DEFINE MATCHTYPE_COMMENT						'<Comment>'

#DEFINE MATCHTYPE_TIMESTAMP						'<TimeStamp>'
#DEFINE MATCHTYPE_FILEDATE						'<FileDate>'
#DEFINE MATCHTYPE_UNKNOWN						'<Unknown>'
#DEFINE MATCHTYPE_TXT							'<Txt>'

#DEFINE MATCHTYPE_INCLUDE_FILE					'<Include File>'

#DEFINE MATCHTYPE_FRX_EXPR					'<Expr>'
#DEFINE MATCHTYPE_FRX_SUPEXPR				'<Supexpr>'
#DEFINE MATCHTYPE_FRX_NAME					'<Name>'
#DEFINE MATCHTYPE_FRX_TAG					'<Tag>'
#DEFINE MATCHTYPE_FRX_TAG2					'<Tag2>'
#DEFINE MATCHTYPE_FRX_PICTURE				'<Picture>'

#DEFINE GF_SEARCH_TYPE_PLAIN	1

#DEFINE GF_SEARCH_MODE_PLAIN	1
#DEFINE GF_SEARCH_MODE_LIKE		2
#DEFINE GF_SEARCH_MODE_REGEX	3

#DEFINE CRLH Chr(13) + Chr(10)
#DEFINE CRLF Chr[13] + Chr[10]
#DEFINE CR Chr(13)
#DEFINE LF Chr(10)
#DEFINE Tab Chr[9]


*-----------------------------------------------------------------------------------
* This section is related to Replace operations:


#DEFINE GF_REPLACE_SUCCESS							 1	
#DEFINE GF_REPLACE_RECORD_IS_NOT_MARKED_FOR_REPLACE	-1
#DEFINE GF_REPLACE_FILE_HAS_ALREADY_BEEN_PROCESSED	-2
#DEFINE GF_REPLACE_BACKUP_ERROR						-3
#DEFINE GF_REPLACE_UNABLE_TO_USE_TABLE_FOR_REPLACE	-4
#DEFINE GF_REPLACE_FILE_NOT_FOUND					-5
#DEFINE GF_REPLACE_ERROR_LOCATING_RECORD_IN_FILE	-6