	#DEFINE GOFISH_APP_NAME 'GoFish5'
	#DEFINE GOFISH_APP_FILE  'GoFish5.app'
	#DEFINE GOFISH_VERSION '5.1.004'
	#DEFINE GOFISH_BUILDDATE '1. November 2022, '
	#DEFINE GOFISH_DBUILDDATE Date(2022,11, 1)
	#DEFINE GOFISH_DOWNLOAD_URL 'https://raw.githubusercontent.com/VFPX/GoFish/master/Source/Source.zip'
	#DEFINE GOFISH_VERSION_STRING_FOR_VERSION_FILE 'GoFish5 - 5.1.004 - 1. November 2022,  - 20221101'
	#DEFINE THOR_TOOL_NAME	'Thor_Tool_GoFish5'
	#DEFINE VERSON_FILE_URL	'https://github.com/VFPX/GoFish/_GoFishVersionFile.txt'
	#DEFINE VERSION_LOCAL_FILE 'GoFishVersionFile.txt'
	#DEFINE GOFISH_HOME_PAGE 'https://github.com/VFPX/GoFish'
