	#DEFINE GOFISH_APP_NAME 'GoFish'
	#DEFINE GOFISH_APP_FILE  'GoFish.app'
	#DEFINE GOFISH_VERSION '7.0.05 Beta'
	#DEFINE GOFISH_BUILDDATE 'February 29, 2024'
	#DEFINE GOFISH_DBUILDDATE Date(2024,2, 29)
	#DEFINE GOFISH_DOWNLOAD_URL 'https://raw.githubusercontent.com/VFPX/GoFish/master/Source/Source.zip'
	#DEFINE GOFISH_VERSION_STRING_FOR_VERSION_FILE 'GoFish - 7.0.05 Beta - February 29, 2024 - 20240229'
	#DEFINE THOR_TOOL_NAME	'Thor_Tool_GoFish'
	#DEFINE VERSON_FILE_URL	'https://github.com/VFPX/GoFish/_GoFishVersionFile.txt'
	#DEFINE VERSION_LOCAL_FILE 'GoFishVersionFile.txt'
	#DEFINE GOFISH_HOME_PAGE 'https://github.com/VFPX/GoFish'
